compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
mixed_precision: bf16
main_training_function: main
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  zero3_init_flag: true
  gradient_clipping: 1.0
  train_batch_size: auto
  train_micro_batch_size_per_gpu: auto
  gradient_accumulation_steps: 1
  zero_allow_untested_optimizer: true
  fp16:
    enabled: auto
    loss_scale: 0
    loss_scale_window: 1000
    initial_scale_power: 16
    hysteresis: 2
    min_loss_scale: 1
  bf16:
    enabled: auto
  zero_optimization:
    stage: 3
    overlap_comm: false
    contiguous_gradients: true
    sub_group_size: 1000000000
    reduce_bucket_size: auto
    stage3_prefetch_bucket_size: auto
    stage3_param_persistence_threshold: auto
    stage3_max_live_parameters: 1000000000
    stage3_max_reuse_distance: 1000000000
    stage3_gather_16bit_weights_on_model_save: true
